# Copyright IO ANALYTICA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: nginx-static
version: 0.1.0
appVersion: "1.0.0"
type: application

description: >-
  Helm chart for deploying a static nginx-served website with optional
  HPA-driven scaling, a PodDisruptionBudget, a primary ingress, and any
  number of optional redirect ingresses.

home: https://github.com/ioanalytica/nginx-static
sources:
  - https://github.com/ioanalytica/nginx-static

maintainers:
  - name: IO ANALYTICA
    url: https://ioanalytica.com

keywords:
  - nginx
  - static
  - website

dependencies:
  - name: common
    repository: oci://ghcr.io/ioanalytica/charts
    version: 0.1.x

annotations:
  category: Web
  licenses: Apache-2.0
